# units that stay the same
mcf:
  long: mcf
  short: mcf
tons:
  long: tons
  short: tons
short tons:
  long: short tons
  short: short tons
# oil and gas
bbl:
  long: barrels
  short: bbl
barrels:
  long: barrels
  short: bbl
gal:
  long: gallons
  short: gal
# units of energy
kilowatt hours:
  short: kWh
  long: kilowatt hours
megawatt hours:
  short: Mwh
  long: megawatt hours
  suffix: energy
# geothermal energy
electrical generation, thousands of pounds:
  short: klb
  long: thousand pounds
  suffix: energy
  title: electrical generation
direct utilization, millions of btus:
  short: MMBTUs
  long: million BTUs
  suffix: energy
  title: direct use
electrical generation, kilowatt hours:
  short: kWh
  long: kilowatt hours
  suffix: energy
  title: electrical generation
electrical generation, other:
  short: units
  long: units
  suffix: energy
  title: electrical generation
direct use, millions of gallons:
  short: Mgal
  long: million gallons
  suffix: energy
  title: direct use
direct utilization, hundreds of gallons:
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
Geothermal - Direct Utilization, Other (cgal):
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
cgal:
  short: cgal
  long: hundred gallons
  suffix: energy
  title: direct use
sulfur:
  short: sulfur
  long: sulfur
  suffix: energy
  title: sulfur
# misc
tickets/pounds:
  short: lbs
  long: tickets/pounds
tons- equivalent:
  short: tons
  long: equivalent tons

